"""initial schema

Revision ID: d3e997a368f6
Revises: 
Create Date: 2026-08-12 01:31:32.451624
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'd3e997a368f6'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('exchange', sa.String(length=8), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('board', sa.Enum('MAINBOARD', 'SME', name='board'), nullable=False),
    sa.Column('status', sa.Enum('UPCOMING', 'OPEN', 'CLOSED', 'LISTED', name='ipostatus'), nullable=False),
    sa.Column('series', sa.String(length=8), nullable=True),
    sa.Column('open_date', sa.Date(), nullable=True),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('allotment_date', sa.Date(), nullable=True),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('price_band_min', sa.Float(), nullable=True),
    sa.Column('price_band_max', sa.Float(), nullable=True),
    sa.Column('issue_price', sa.Float(), nullable=True),
    sa.Column('face_value', sa.Float(), nullable=True),
    sa.Column('lot_size', sa.Integer(), nullable=True),
    sa.Column('issue_size', sa.Float(), nullable=True),
    sa.Column('registrar', sa.String(length=255), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'exchange', name='uq_ipo_symbol_exchange')
    )
    op.create_index(op.f('ix_ipos_close_date'), 'ipos', ['close_date'], unique=False)
    op.create_index(op.f('ix_ipos_open_date'), 'ipos', ['open_date'], unique=False)
    op.create_index(op.f('ix_ipos_status'), 'ipos', ['status'], unique=False)
    op.create_index(op.f('ix_ipos_symbol'), 'ipos', ['symbol'], unique=False)
    op.create_table('magic_link_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_magic_link_tokens_email'), 'magic_link_tokens', ['email'], unique=False)
    op.create_index(op.f('ix_magic_link_tokens_token_hash'), 'magic_link_tokens', ['token_hash'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ipo_id', sa.Integer(), nullable=True),
    sa.Column('rule_type', sa.Enum('LAST_DAY', 'OPEN_DAY', 'ALLOTMENT_DAY', 'LISTING_DAY', 'GMP_ABOVE', 'SUBSCRIPTION_ABOVE', name='ruletype'), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('fire_hours_ist', sa.JSON(), nullable=False),
    sa.Column('board_filter', sa.Enum('MAINBOARD', 'SME', name='board'), nullable=True),
    sa.Column('watchlist_only', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ipo_id'], ['ipos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_user_id'), 'alert_rules', ['user_id'], unique=False)
    op.create_table('gmp_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipo_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmp_value', sa.Float(), nullable=True),
    sa.Column('gmp_pct', sa.Float(), nullable=True),
    sa.Column('estimated_listing_price', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['ipo_id'], ['ipos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gmp_ipo_captured', 'gmp_snapshots', ['ipo_id', 'captured_at'], unique=False)
    op.create_index(op.f('ix_gmp_snapshots_captured_at'), 'gmp_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_gmp_snapshots_ipo_id'), 'gmp_snapshots', ['ipo_id'], unique=False)
    op.create_table('notification_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'TELEGRAM', 'WEBPUSH', 'INAPP', name='channel'), nullable=False),
    sa.Column('destination', sa.Text(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'channel', 'destination', name='uq_channel_dest')
    )
    op.create_index(op.f('ix_notification_channels_user_id'), 'notification_channels', ['user_id'], unique=False)
    op.create_table('subscription_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipo_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.Enum('QIB', 'NII', 'RETAIL', 'EMPLOYEE', 'OTHER', 'TOTAL', name='subcategory'), nullable=False),
    sa.Column('shares_offered', sa.Float(), nullable=True),
    sa.Column('shares_bid', sa.Float(), nullable=True),
    sa.Column('times_subscribed', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ipo_id'], ['ipos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ipo_id', 'category', 'captured_at', name='uq_sub_point')
    )
    op.create_index('ix_sub_ipo_captured', 'subscription_snapshots', ['ipo_id', 'captured_at'], unique=False)
    op.create_index(op.f('ix_subscription_snapshots_captured_at'), 'subscription_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_subscription_snapshots_ipo_id'), 'subscription_snapshots', ['ipo_id'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ipo_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ipo_id'], ['ipos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ipo_id', name='uq_watch_user_ipo')
    )
    op.create_index(op.f('ix_watchlist_items_ipo_id'), 'watchlist_items', ['ipo_id'], unique=False)
    op.create_index(op.f('ix_watchlist_items_user_id'), 'watchlist_items', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ipo_id', sa.Integer(), nullable=True),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.Enum('EMAIL', 'TELEGRAM', 'WEBPUSH', 'INAPP', name='channel'), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='notificationstatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ipo_id'], ['ipos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key', name='uq_notification_dedupe')
    )
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_watchlist_items_user_id'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_ipo_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_subscription_snapshots_ipo_id'), table_name='subscription_snapshots')
    op.drop_index(op.f('ix_subscription_snapshots_captured_at'), table_name='subscription_snapshots')
    op.drop_index('ix_sub_ipo_captured', table_name='subscription_snapshots')
    op.drop_table('subscription_snapshots')
    op.drop_index(op.f('ix_notification_channels_user_id'), table_name='notification_channels')
    op.drop_table('notification_channels')
    op.drop_index(op.f('ix_gmp_snapshots_ipo_id'), table_name='gmp_snapshots')
    op.drop_index(op.f('ix_gmp_snapshots_captured_at'), table_name='gmp_snapshots')
    op.drop_index('ix_gmp_ipo_captured', table_name='gmp_snapshots')
    op.drop_table('gmp_snapshots')
    op.drop_index(op.f('ix_alert_rules_user_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_magic_link_tokens_token_hash'), table_name='magic_link_tokens')
    op.drop_index(op.f('ix_magic_link_tokens_email'), table_name='magic_link_tokens')
    op.drop_table('magic_link_tokens')
    op.drop_index(op.f('ix_ipos_symbol'), table_name='ipos')
    op.drop_index(op.f('ix_ipos_status'), table_name='ipos')
    op.drop_index(op.f('ix_ipos_open_date'), table_name='ipos')
    op.drop_index(op.f('ix_ipos_close_date'), table_name='ipos')
    op.drop_table('ipos')
    # ### end Alembic commands ###
